// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: blob.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BlobHeader contains metadata for a blob stored in S3.
type BlobHeader struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Timestamp  uint64                 `protobuf:"varint,1,opt,name=timestamp,proto3"`
	xxx_hidden_Blocks     *[]*BlockEntry         `protobuf:"bytes,2,rep,name=blocks,proto3"`
	xxx_hidden_HeaderSize uint32                 `protobuf:"varint,3,opt,name=header_size,json=headerSize,proto3"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *BlobHeader) Reset() {
	*x = BlobHeader{}
	mi := &file_blob_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlobHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobHeader) ProtoMessage() {}

func (x *BlobHeader) ProtoReflect() protoreflect.Message {
	mi := &file_blob_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BlobHeader) GetTimestamp() uint64 {
	if x != nil {
		return x.xxx_hidden_Timestamp
	}
	return 0
}

func (x *BlobHeader) GetBlocks() []*BlockEntry {
	if x != nil {
		if x.xxx_hidden_Blocks != nil {
			return *x.xxx_hidden_Blocks
		}
	}
	return nil
}

func (x *BlobHeader) GetHeaderSize() uint32 {
	if x != nil {
		return x.xxx_hidden_HeaderSize
	}
	return 0
}

func (x *BlobHeader) SetTimestamp(v uint64) {
	x.xxx_hidden_Timestamp = v
}

func (x *BlobHeader) SetBlocks(v []*BlockEntry) {
	x.xxx_hidden_Blocks = &v
}

func (x *BlobHeader) SetHeaderSize(v uint32) {
	x.xxx_hidden_HeaderSize = v
}

type BlobHeader_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Timestamp in milliseconds since epoch when the blob was created.
	Timestamp uint64
	// Blocks describes the device ranges contained in this blob.
	// Data blocks have their data stored sequentially in the blob's data section.
	// Hole blocks have no corresponding data (they represent trimmed/zeroed regions).
	Blocks []*BlockEntry
	// Total header size in bytes (Magic + Version + HeaderLen + Proto).
	// Used to compute data offsets when reading from blobs.
	HeaderSize uint32
}

func (b0 BlobHeader_builder) Build() *BlobHeader {
	m0 := &BlobHeader{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Timestamp = b.Timestamp
	x.xxx_hidden_Blocks = &b.Blocks
	x.xxx_hidden_HeaderSize = b.HeaderSize
	return m0
}

// BlockEntry describes a single block within a blob.
type BlockEntry struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Offset uint64                 `protobuf:"varint,1,opt,name=offset,proto3"`
	xxx_hidden_Length uint64                 `protobuf:"varint,2,opt,name=length,proto3"`
	xxx_hidden_IsHole bool                   `protobuf:"varint,3,opt,name=is_hole,json=isHole,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BlockEntry) Reset() {
	*x = BlockEntry{}
	mi := &file_blob_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockEntry) ProtoMessage() {}

func (x *BlockEntry) ProtoReflect() protoreflect.Message {
	mi := &file_blob_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BlockEntry) GetOffset() uint64 {
	if x != nil {
		return x.xxx_hidden_Offset
	}
	return 0
}

func (x *BlockEntry) GetLength() uint64 {
	if x != nil {
		return x.xxx_hidden_Length
	}
	return 0
}

func (x *BlockEntry) GetIsHole() bool {
	if x != nil {
		return x.xxx_hidden_IsHole
	}
	return false
}

func (x *BlockEntry) SetOffset(v uint64) {
	x.xxx_hidden_Offset = v
}

func (x *BlockEntry) SetLength(v uint64) {
	x.xxx_hidden_Length = v
}

func (x *BlockEntry) SetIsHole(v bool) {
	x.xxx_hidden_IsHole = v
}

type BlockEntry_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Device offset where this block starts.
	Offset uint64
	// Length of this block in bytes.
	Length uint64
	// If true, this block is a hole (trimmed/zeroed region) with no data.
	// Reads to this region should return zeros.
	IsHole bool
}

func (b0 BlockEntry_builder) Build() *BlockEntry {
	m0 := &BlockEntry{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Offset = b.Offset
	x.xxx_hidden_Length = b.Length
	x.xxx_hidden_IsHole = b.IsHole
	return m0
}

// IndexSegment represents a batch of blob headers stored in S3.
// Segments cover a range of blob timestamps and are used for
// cold-start recovery without full blob listing.
type IndexSegment struct {
	state                              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Epoch                   int32                  `protobuf:"varint,1,opt,name=epoch,proto3"`
	xxx_hidden_StartTimestampExclusive int64                  `protobuf:"varint,2,opt,name=start_timestamp_exclusive,json=startTimestampExclusive,proto3"`
	xxx_hidden_EndTimestampInclusive   int64                  `protobuf:"varint,3,opt,name=end_timestamp_inclusive,json=endTimestampInclusive,proto3"`
	xxx_hidden_Blobs                   *[]*IndexSegmentEntry  `protobuf:"bytes,4,rep,name=blobs,proto3"`
	unknownFields                      protoimpl.UnknownFields
	sizeCache                          protoimpl.SizeCache
}

func (x *IndexSegment) Reset() {
	*x = IndexSegment{}
	mi := &file_blob_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexSegment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexSegment) ProtoMessage() {}

func (x *IndexSegment) ProtoReflect() protoreflect.Message {
	mi := &file_blob_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *IndexSegment) GetEpoch() int32 {
	if x != nil {
		return x.xxx_hidden_Epoch
	}
	return 0
}

func (x *IndexSegment) GetStartTimestampExclusive() int64 {
	if x != nil {
		return x.xxx_hidden_StartTimestampExclusive
	}
	return 0
}

func (x *IndexSegment) GetEndTimestampInclusive() int64 {
	if x != nil {
		return x.xxx_hidden_EndTimestampInclusive
	}
	return 0
}

func (x *IndexSegment) GetBlobs() []*IndexSegmentEntry {
	if x != nil {
		if x.xxx_hidden_Blobs != nil {
			return *x.xxx_hidden_Blobs
		}
	}
	return nil
}

func (x *IndexSegment) SetEpoch(v int32) {
	x.xxx_hidden_Epoch = v
}

func (x *IndexSegment) SetStartTimestampExclusive(v int64) {
	x.xxx_hidden_StartTimestampExclusive = v
}

func (x *IndexSegment) SetEndTimestampInclusive(v int64) {
	x.xxx_hidden_EndTimestampInclusive = v
}

func (x *IndexSegment) SetBlobs(v []*IndexSegmentEntry) {
	x.xxx_hidden_Blobs = &v
}

type IndexSegment_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Compaction epoch. Epoch 0 is for normal segments.
	// Higher epochs are for compacted segments that supersede lower-epoch ones.
	Epoch int32
	// Exclusive lower bound of this segment's coverage range.
	// The segment covers blobs with timestamps in (start, end].
	// Equal to the previous segment's end_timestamp_inclusive, or 0 for the first.
	StartTimestampExclusive int64
	// Inclusive upper bound of this segment's coverage range.
	EndTimestampInclusive int64
	// Blob entries in this segment, sorted by timestamp.
	Blobs []*IndexSegmentEntry
}

func (b0 IndexSegment_builder) Build() *IndexSegment {
	m0 := &IndexSegment{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Epoch = b.Epoch
	x.xxx_hidden_StartTimestampExclusive = b.StartTimestampExclusive
	x.xxx_hidden_EndTimestampInclusive = b.EndTimestampInclusive
	x.xxx_hidden_Blobs = &b.Blobs
	return m0
}

// IndexSegmentEntry represents a single blob's metadata in a segment.
type IndexSegmentEntry struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id     string                 `protobuf:"bytes,1,opt,name=id,proto3"`
	xxx_hidden_Header *BlobHeader            `protobuf:"bytes,2,opt,name=header,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *IndexSegmentEntry) Reset() {
	*x = IndexSegmentEntry{}
	mi := &file_blob_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexSegmentEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexSegmentEntry) ProtoMessage() {}

func (x *IndexSegmentEntry) ProtoReflect() protoreflect.Message {
	mi := &file_blob_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *IndexSegmentEntry) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *IndexSegmentEntry) GetHeader() *BlobHeader {
	if x != nil {
		return x.xxx_hidden_Header
	}
	return nil
}

func (x *IndexSegmentEntry) SetId(v string) {
	x.xxx_hidden_Id = v
}

func (x *IndexSegmentEntry) SetHeader(v *BlobHeader) {
	x.xxx_hidden_Header = v
}

func (x *IndexSegmentEntry) HasHeader() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Header != nil
}

func (x *IndexSegmentEntry) ClearHeader() {
	x.xxx_hidden_Header = nil
}

type IndexSegmentEntry_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Blob ID (format: {timestamp_ms}-{random_hex}).
	Id string
	// Blob header metadata.
	Header *BlobHeader
}

func (b0 IndexSegmentEntry_builder) Build() *IndexSegmentEntry {
	m0 := &IndexSegmentEntry{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Header = b.Header
	return m0
}

var File_blob_proto protoreflect.FileDescriptor

const file_blob_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"blob.proto\x12\n" +
	"cloudblock\"{\n" +
	"\n" +
	"BlobHeader\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x04R\ttimestamp\x12.\n" +
	"\x06blocks\x18\x02 \x03(\v2\x16.cloudblock.BlockEntryR\x06blocks\x12\x1f\n" +
	"\vheader_size\x18\x03 \x01(\rR\n" +
	"headerSize\"U\n" +
	"\n" +
	"BlockEntry\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x04R\x06offset\x12\x16\n" +
	"\x06length\x18\x02 \x01(\x04R\x06length\x12\x17\n" +
	"\ais_hole\x18\x03 \x01(\bR\x06isHole\"\xcd\x01\n" +
	"\fIndexSegment\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x05R\x05epoch\x12:\n" +
	"\x19start_timestamp_exclusive\x18\x02 \x01(\x03R\x17startTimestampExclusive\x126\n" +
	"\x17end_timestamp_inclusive\x18\x03 \x01(\x03R\x15endTimestampInclusive\x123\n" +
	"\x05blobs\x18\x04 \x03(\v2\x1d.cloudblock.IndexSegmentEntryR\x05blobs\"S\n" +
	"\x11IndexSegmentEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12.\n" +
	"\x06header\x18\x02 \x01(\v2\x16.cloudblock.BlobHeaderR\x06headerB;Z9github.com/anupcshan/cloudblockdev/internal/cloudblock/pbb\x06proto3"

var file_blob_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_blob_proto_goTypes = []any{
	(*BlobHeader)(nil),        // 0: cloudblock.BlobHeader
	(*BlockEntry)(nil),        // 1: cloudblock.BlockEntry
	(*IndexSegment)(nil),      // 2: cloudblock.IndexSegment
	(*IndexSegmentEntry)(nil), // 3: cloudblock.IndexSegmentEntry
}
var file_blob_proto_depIdxs = []int32{
	1, // 0: cloudblock.BlobHeader.blocks:type_name -> cloudblock.BlockEntry
	3, // 1: cloudblock.IndexSegment.blobs:type_name -> cloudblock.IndexSegmentEntry
	0, // 2: cloudblock.IndexSegmentEntry.header:type_name -> cloudblock.BlobHeader
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_blob_proto_init() }
func file_blob_proto_init() {
	if File_blob_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blob_proto_rawDesc), len(file_blob_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_blob_proto_goTypes,
		DependencyIndexes: file_blob_proto_depIdxs,
		MessageInfos:      file_blob_proto_msgTypes,
	}.Build()
	File_blob_proto = out.File
	file_blob_proto_goTypes = nil
	file_blob_proto_depIdxs = nil
}
